#!/usr/bin/env ruby

require 'grpc'
require 'socket'
require_relative './yggdrasil_services_pb'

class ForemanClient < Yggdrasil::Worker::Service
  # despite the name, this is actually receiving data from server
  def send(data)

  end
end

stub = Yggdrasil::Dispatcher::Stub.new(ENV['YGG_SOCKET_ADDR'], :this_channel_is_insecure)
response = stub.register(Yggdrasil::RegistrationRequest.new(handler: 'foreman', pid: Process.pid))


if response.registered
  socket_address = response.address

  server = GRPC::RpcServer.new
  server.add_insecure_port(socket_address)
  server.handle(ForemanClient.new)
  s.run_till_terminated_or_interrupted([1, 'int', 'SIGQUIT'])
end
