# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yggdrasil.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("yggdrasil.proto", :syntax => :proto3) do
    add_message "yggdrasil.Empty" do
    end
    add_message "yggdrasil.RegistrationRequest" do
      optional :handler, :string, 1
      optional :pid, :int64, 2
      optional :detached_content, :bool, 3
      map :features, :string, :string, 4
    end
    add_message "yggdrasil.RegistrationResponse" do
      optional :registered, :bool, 1
      optional :address, :string, 2
    end
    add_message "yggdrasil.Data" do
      optional :message_id, :string, 1
      map :metadata, :string, :string, 2
      optional :content, :bytes, 3
      optional :response_to, :string, 4
      optional :directive, :string, 5
    end
    add_message "yggdrasil.Receipt" do
    end
  end
end

module Yggdrasil
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("yggdrasil.Empty").msgclass
  RegistrationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("yggdrasil.RegistrationRequest").msgclass
  RegistrationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("yggdrasil.RegistrationResponse").msgclass
  Data = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("yggdrasil.Data").msgclass
  Receipt = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("yggdrasil.Receipt").msgclass
end
